"""add applicants_page tables

Revision ID: 0007b05c794e
Revises: 955a5651a012
Create Date: 2026-04-09 19:21:29.721777

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '0007b05c794e'
down_revision: Union[str, None] = '955a5651a012'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('applicants_doc_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_uz', sa.String(length=300), nullable=False),
    sa.Column('title_ru', sa.String(length=300), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('items', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants_faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('question_uz', sa.String(length=500), nullable=False),
    sa.Column('question_ru', sa.String(length=500), nullable=False),
    sa.Column('question_en', sa.String(length=500), nullable=False),
    sa.Column('answer_uz', sa.Text(), nullable=False),
    sa.Column('answer_ru', sa.Text(), nullable=False),
    sa.Column('answer_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants_forms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_uz', sa.String(length=300), nullable=False),
    sa.Column('title_ru', sa.String(length=300), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('desc_uz', sa.Text(), nullable=False),
    sa.Column('desc_ru', sa.Text(), nullable=False),
    sa.Column('desc_en', sa.Text(), nullable=False),
    sa.Column('features', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cta_label_uz', sa.String(length=120), nullable=True),
    sa.Column('cta_label_ru', sa.String(length=120), nullable=True),
    sa.Column('cta_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('hero_title_uz', sa.String(length=500), nullable=True),
    sa.Column('hero_title_ru', sa.String(length=500), nullable=True),
    sa.Column('hero_title_en', sa.String(length=500), nullable=True),
    sa.Column('hero_subtitle_uz', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_ru', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_en', sa.Text(), nullable=True),
    sa.Column('steps_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('steps_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('steps_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('steps_title_uz', sa.String(length=500), nullable=True),
    sa.Column('steps_title_ru', sa.String(length=500), nullable=True),
    sa.Column('steps_title_en', sa.String(length=500), nullable=True),
    sa.Column('forms_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('forms_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('forms_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('forms_title_uz', sa.String(length=500), nullable=True),
    sa.Column('forms_title_ru', sa.String(length=500), nullable=True),
    sa.Column('forms_title_en', sa.String(length=500), nullable=True),
    sa.Column('timeline_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('timeline_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('timeline_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('timeline_title_uz', sa.String(length=500), nullable=True),
    sa.Column('timeline_title_ru', sa.String(length=500), nullable=True),
    sa.Column('timeline_title_en', sa.String(length=500), nullable=True),
    sa.Column('docs_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('docs_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('docs_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('docs_title_uz', sa.String(length=500), nullable=True),
    sa.Column('docs_title_ru', sa.String(length=500), nullable=True),
    sa.Column('docs_title_en', sa.String(length=500), nullable=True),
    sa.Column('faq_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('faq_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('faq_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('faq_title_uz', sa.String(length=500), nullable=True),
    sa.Column('faq_title_ru', sa.String(length=500), nullable=True),
    sa.Column('faq_title_en', sa.String(length=500), nullable=True),
    sa.Column('cta_title_uz', sa.String(length=500), nullable=True),
    sa.Column('cta_title_ru', sa.String(length=500), nullable=True),
    sa.Column('cta_title_en', sa.String(length=500), nullable=True),
    sa.Column('cta_text_uz', sa.Text(), nullable=True),
    sa.Column('cta_text_ru', sa.Text(), nullable=True),
    sa.Column('cta_text_en', sa.Text(), nullable=True),
    sa.Column('cta_primary_label_uz', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_label_ru', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_url', sa.String(length=500), nullable=True),
    sa.Column('cta_primary_external', sa.Boolean(), nullable=False),
    sa.Column('cta_phone_label', sa.String(length=60), nullable=True),
    sa.Column('cta_phone_url', sa.String(length=60), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('number', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('title_uz', sa.String(length=255), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('desc_uz', sa.Text(), nullable=False),
    sa.Column('desc_ru', sa.Text(), nullable=False),
    sa.Column('desc_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('applicants_timeline',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('month_uz', sa.String(length=60), nullable=False),
    sa.Column('month_ru', sa.String(length=60), nullable=False),
    sa.Column('month_en', sa.String(length=60), nullable=False),
    sa.Column('text_uz', sa.Text(), nullable=False),
    sa.Column('text_ru', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('applicants_timeline')
    op.drop_table('applicants_steps')
    op.drop_table('applicants_page')
    op.drop_table('applicants_forms')
    op.drop_table('applicants_faqs')
    op.drop_table('applicants_doc_categories')
    # ### end Alembic commands ###
