"""add contact_page table

Revision ID: 0208a9c75ba5
Revises: 1d8fc9b76868
Create Date: 2026-04-10 09:00:28.319234

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0208a9c75ba5'
down_revision: Union[str, None] = '1d8fc9b76868'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('contact_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('hero_title_uz', sa.String(length=500), nullable=True),
    sa.Column('hero_title_ru', sa.String(length=500), nullable=True),
    sa.Column('hero_title_en', sa.String(length=500), nullable=True),
    sa.Column('hero_subtitle_uz', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_ru', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_en', sa.Text(), nullable=True),
    sa.Column('address_uz', sa.String(length=500), nullable=True),
    sa.Column('address_ru', sa.String(length=500), nullable=True),
    sa.Column('address_en', sa.String(length=500), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('working_hours_uz', sa.String(length=255), nullable=True),
    sa.Column('working_hours_ru', sa.String(length=255), nullable=True),
    sa.Column('working_hours_en', sa.String(length=255), nullable=True),
    sa.Column('form_title_uz', sa.String(length=255), nullable=True),
    sa.Column('form_title_ru', sa.String(length=255), nullable=True),
    sa.Column('form_title_en', sa.String(length=255), nullable=True),
    sa.Column('form_subtitle_uz', sa.Text(), nullable=True),
    sa.Column('form_subtitle_ru', sa.Text(), nullable=True),
    sa.Column('form_subtitle_en', sa.Text(), nullable=True),
    sa.Column('map_embed_url', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('contact_page')
    # ### end Alembic commands ###
