"""add vacancies_page tables

Revision ID: 1d8fc9b76868
Revises: a53f649e110c
Create Date: 2026-04-09 20:44:26.435361

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '1d8fc9b76868'
down_revision: Union[str, None] = 'a53f649e110c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vacancies',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_open', sa.Boolean(), nullable=False),
    sa.Column('title_uz', sa.String(length=500), nullable=False),
    sa.Column('title_ru', sa.String(length=500), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=False),
    sa.Column('department_uz', sa.String(length=255), nullable=False),
    sa.Column('department_ru', sa.String(length=255), nullable=False),
    sa.Column('department_en', sa.String(length=255), nullable=False),
    sa.Column('employment_type', sa.String(length=20), server_default='full_time', nullable=False),
    sa.Column('location_uz', sa.String(length=255), nullable=False),
    sa.Column('location_ru', sa.String(length=255), nullable=False),
    sa.Column('location_en', sa.String(length=255), nullable=False),
    sa.Column('description_uz', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('requirements_uz', sa.Text(), nullable=False),
    sa.Column('requirements_ru', sa.Text(), nullable=False),
    sa.Column('requirements_en', sa.Text(), nullable=False),
    sa.Column('salary', sa.String(length=120), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('apply_url', sa.String(length=500), nullable=True),
    sa.Column('posted_at', sa.Date(), nullable=True),
    sa.Column('deadline', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('vacancies_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('hero_title_uz', sa.String(length=500), nullable=True),
    sa.Column('hero_title_ru', sa.String(length=500), nullable=True),
    sa.Column('hero_title_en', sa.String(length=500), nullable=True),
    sa.Column('hero_subtitle_uz', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_ru', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_en', sa.Text(), nullable=True),
    sa.Column('empty_title_uz', sa.String(length=255), nullable=True),
    sa.Column('empty_title_ru', sa.String(length=255), nullable=True),
    sa.Column('empty_title_en', sa.String(length=255), nullable=True),
    sa.Column('empty_text_uz', sa.Text(), nullable=True),
    sa.Column('empty_text_ru', sa.Text(), nullable=True),
    sa.Column('empty_text_en', sa.Text(), nullable=True),
    sa.Column('cv_title_uz', sa.String(length=255), nullable=True),
    sa.Column('cv_title_ru', sa.String(length=255), nullable=True),
    sa.Column('cv_title_en', sa.String(length=255), nullable=True),
    sa.Column('cv_text_uz', sa.Text(), nullable=True),
    sa.Column('cv_text_ru', sa.Text(), nullable=True),
    sa.Column('cv_text_en', sa.Text(), nullable=True),
    sa.Column('cv_email', sa.String(length=255), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vacancies_page')
    op.drop_table('vacancies')
    # ### end Alembic commands ###
