"""add home settings models

Revision ID: 2a8cdd6313d3
Revises: f630d7709410
Create Date: 2026-04-08 19:42:07.067739

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '2a8cdd6313d3'
down_revision: Union[str, None] = 'f630d7709410'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('faculties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=120), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('description_uz', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculties_slug'), 'faculties', ['slug'], unique=True)
    op.create_table('hero_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('page', sa.String(length=50), nullable=False),
    sa.Column('variant', sa.String(length=40), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('title_uz', sa.String(length=500), nullable=True),
    sa.Column('title_ru', sa.String(length=500), nullable=True),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('title_highlight_uz', sa.String(length=255), nullable=True),
    sa.Column('title_highlight_ru', sa.String(length=255), nullable=True),
    sa.Column('title_highlight_en', sa.String(length=255), nullable=True),
    sa.Column('title_tail_uz', sa.String(length=255), nullable=True),
    sa.Column('title_tail_ru', sa.String(length=255), nullable=True),
    sa.Column('title_tail_en', sa.String(length=255), nullable=True),
    sa.Column('subtitle_uz', sa.Text(), nullable=True),
    sa.Column('subtitle_ru', sa.Text(), nullable=True),
    sa.Column('subtitle_en', sa.Text(), nullable=True),
    sa.Column('bg_image', sa.String(length=500), nullable=True),
    sa.Column('bg_video', sa.String(length=500), nullable=True),
    sa.Column('bg_video_poster', sa.String(length=500), nullable=True),
    sa.Column('side_image', sa.String(length=500), nullable=True),
    sa.Column('overlay_opacity', sa.Integer(), nullable=False),
    sa.Column('cta_primary_label_uz', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_label_ru', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_url', sa.String(length=500), nullable=True),
    sa.Column('cta_primary_external', sa.Boolean(), nullable=False),
    sa.Column('cta_secondary_label_uz', sa.String(length=120), nullable=True),
    sa.Column('cta_secondary_label_ru', sa.String(length=120), nullable=True),
    sa.Column('cta_secondary_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_secondary_url', sa.String(length=500), nullable=True),
    sa.Column('cta_secondary_external', sa.Boolean(), nullable=False),
    sa.Column('show_particles', sa.Boolean(), nullable=False),
    sa.Column('show_scroll_indicator', sa.Boolean(), nullable=False),
    sa.Column('show_trust_badges', sa.Boolean(), nullable=False),
    sa.Column('show_floating_cards', sa.Boolean(), nullable=False),
    sa.Column('quote_text_uz', sa.Text(), nullable=True),
    sa.Column('quote_text_ru', sa.Text(), nullable=True),
    sa.Column('quote_text_en', sa.Text(), nullable=True),
    sa.Column('quote_author_uz', sa.String(length=255), nullable=True),
    sa.Column('quote_author_ru', sa.String(length=255), nullable=True),
    sa.Column('quote_author_en', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_hero_settings_page'), 'hero_settings', ['page'], unique=True)
    op.create_table('home_admission_steps',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('number', sa.String(length=8), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('title_uz', sa.String(length=255), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('desc_uz', sa.Text(), nullable=False),
    sa.Column('desc_ru', sa.Text(), nullable=False),
    sa.Column('desc_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_campus',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('main_image', sa.String(length=500), nullable=True),
    sa.Column('image_2', sa.String(length=500), nullable=True),
    sa.Column('image_3', sa.String(length=500), nullable=True),
    sa.Column('video_url', sa.String(length=500), nullable=True),
    sa.Column('eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('title_uz', sa.String(length=500), nullable=True),
    sa.Column('title_ru', sa.String(length=500), nullable=True),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('text_uz', sa.Text(), nullable=True),
    sa.Column('text_ru', sa.Text(), nullable=True),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('bullets', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('cta_label_uz', sa.String(length=120), nullable=True),
    sa.Column('cta_label_ru', sa.String(length=120), nullable=True),
    sa.Column('cta_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_faqs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('question_uz', sa.String(length=500), nullable=False),
    sa.Column('question_ru', sa.String(length=500), nullable=False),
    sa.Column('question_en', sa.String(length=500), nullable=False),
    sa.Column('answer_uz', sa.Text(), nullable=False),
    sa.Column('answer_ru', sa.Text(), nullable=False),
    sa.Column('answer_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_final_cta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('title_uz', sa.String(length=500), nullable=True),
    sa.Column('title_ru', sa.String(length=500), nullable=True),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('text_uz', sa.Text(), nullable=True),
    sa.Column('text_ru', sa.Text(), nullable=True),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('cta_label_uz', sa.String(length=120), nullable=True),
    sa.Column('cta_label_ru', sa.String(length=120), nullable=True),
    sa.Column('cta_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_url', sa.String(length=500), nullable=True),
    sa.Column('cta_external', sa.Boolean(), nullable=False),
    sa.Column('phone_label', sa.String(length=60), nullable=True),
    sa.Column('phone_url', sa.String(length=60), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_intro_pillars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('title_uz', sa.String(length=200), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('desc_uz', sa.Text(), nullable=False),
    sa.Column('desc_ru', sa.Text(), nullable=False),
    sa.Column('desc_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_licenses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('title_uz', sa.String(length=255), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('issuer_uz', sa.String(length=255), nullable=False),
    sa.Column('issuer_ru', sa.String(length=255), nullable=False),
    sa.Column('issuer_en', sa.String(length=255), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('pdf', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('flag', sa.String(length=20), nullable=False),
    sa.Column('country_uz', sa.String(length=120), nullable=False),
    sa.Column('country_ru', sa.String(length=120), nullable=False),
    sa.Column('country_en', sa.String(length=120), nullable=False),
    sa.Column('count', sa.Integer(), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_quick_actions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('title_uz', sa.String(length=200), nullable=False),
    sa.Column('title_ru', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=False),
    sa.Column('desc_uz', sa.String(length=300), nullable=False),
    sa.Column('desc_ru', sa.String(length=300), nullable=False),
    sa.Column('desc_en', sa.String(length=300), nullable=False),
    sa.Column('url', sa.String(length=500), nullable=False),
    sa.Column('external', sa.Boolean(), nullable=False),
    sa.Column('accent', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_sections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=60), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('title_uz', sa.String(length=500), nullable=True),
    sa.Column('title_ru', sa.String(length=500), nullable=True),
    sa.Column('title_en', sa.String(length=500), nullable=True),
    sa.Column('subtitle_uz', sa.Text(), nullable=True),
    sa.Column('subtitle_ru', sa.Text(), nullable=True),
    sa.Column('subtitle_en', sa.Text(), nullable=True),
    sa.Column('settings', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_home_sections_key'), 'home_sections', ['key'], unique=True)
    op.create_table('home_stats',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('value', sa.String(length=40), nullable=False),
    sa.Column('label_uz', sa.String(length=255), nullable=False),
    sa.Column('label_ru', sa.String(length=255), nullable=False),
    sa.Column('label_en', sa.String(length=255), nullable=False),
    sa.Column('sub_uz', sa.String(length=255), nullable=False),
    sa.Column('sub_ru', sa.String(length=255), nullable=False),
    sa.Column('sub_en', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_testimonials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('role_uz', sa.String(length=255), nullable=False),
    sa.Column('role_ru', sa.String(length=255), nullable=False),
    sa.Column('role_en', sa.String(length=255), nullable=False),
    sa.Column('text_uz', sa.Text(), nullable=False),
    sa.Column('text_ru', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.Column('avatar', sa.String(length=500), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('home_why_cards',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('icon_bg', sa.String(length=60), nullable=False),
    sa.Column('icon_color', sa.String(length=60), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=False),
    sa.Column('number_label_uz', sa.String(length=120), nullable=False),
    sa.Column('number_label_ru', sa.String(length=120), nullable=False),
    sa.Column('number_label_en', sa.String(length=120), nullable=False),
    sa.Column('title_uz', sa.String(length=255), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('desc_uz', sa.Text(), nullable=False),
    sa.Column('desc_ru', sa.Text(), nullable=False),
    sa.Column('desc_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('faculty_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('faculty_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name_uz', sa.String(length=300), nullable=False),
    sa.Column('name_ru', sa.String(length=300), nullable=False),
    sa.Column('name_en', sa.String(length=300), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('bg_class', sa.String(length=120), nullable=False),
    sa.Column('icon_bg_class', sa.String(length=120), nullable=False),
    sa.Column('ring_class', sa.String(length=120), nullable=False),
    sa.Column('duration_uz', sa.String(length=60), nullable=False),
    sa.Column('duration_ru', sa.String(length=60), nullable=False),
    sa.Column('duration_en', sa.String(length=60), nullable=False),
    sa.Column('tuition', sa.String(length=60), nullable=False),
    sa.Column('language_uz', sa.String(length=60), nullable=False),
    sa.Column('language_ru', sa.String(length=60), nullable=False),
    sa.Column('language_en', sa.String(length=60), nullable=False),
    sa.ForeignKeyConstraint(['faculty_id'], ['faculties.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_faculty_programs_faculty_id'), 'faculty_programs', ['faculty_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_faculty_programs_faculty_id'), table_name='faculty_programs')
    op.drop_table('faculty_programs')
    op.drop_table('home_why_cards')
    op.drop_table('home_testimonials')
    op.drop_table('home_stats')
    op.drop_index(op.f('ix_home_sections_key'), table_name='home_sections')
    op.drop_table('home_sections')
    op.drop_table('home_quick_actions')
    op.drop_table('home_partners')
    op.drop_table('home_licenses')
    op.drop_table('home_intro_pillars')
    op.drop_table('home_final_cta')
    op.drop_table('home_faqs')
    op.drop_table('home_campus')
    op.drop_table('home_admission_steps')
    op.drop_index(op.f('ix_hero_settings_page'), table_name='hero_settings')
    op.drop_table('hero_settings')
    op.drop_index(op.f('ix_faculties_slug'), table_name='faculties')
    op.drop_table('faculties')
    # ### end Alembic commands ###
