"""add leaders table

Revision ID: 4a5b7f5fe65d
Revises: e859d64c0470
Create Date: 2026-04-09 12:50:02.079696

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4a5b7f5fe65d'
down_revision: Union[str, None] = 'e859d64c0470'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leaders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('group', sa.String(length=30), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('position_uz', sa.String(length=255), nullable=False),
    sa.Column('position_ru', sa.String(length=255), nullable=False),
    sa.Column('position_en', sa.String(length=255), nullable=False),
    sa.Column('degree_uz', sa.String(length=255), nullable=False),
    sa.Column('degree_ru', sa.String(length=255), nullable=False),
    sa.Column('degree_en', sa.String(length=255), nullable=False),
    sa.Column('bio_uz', sa.Text(), nullable=False),
    sa.Column('bio_ru', sa.Text(), nullable=False),
    sa.Column('bio_en', sa.Text(), nullable=False),
    sa.Column('photo', sa.String(length=500), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leaders_group'), 'leaders', ['group'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_leaders_group'), table_name='leaders')
    op.drop_table('leaders')
    # ### end Alembic commands ###
