"""add gallery_page tables

Revision ID: 4e322f401000
Revises: 0208a9c75ba5
Create Date: 2026-04-10 09:22:04.750158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '4e322f401000'
down_revision: Union[str, None] = '0208a9c75ba5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('gallery_categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=60), nullable=False),
    sa.Column('name_uz', sa.String(length=120), nullable=False),
    sa.Column('name_ru', sa.String(length=120), nullable=False),
    sa.Column('name_en', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_categories_slug'), 'gallery_categories', ['slug'], unique=True)
    op.create_table('gallery_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('hero_title_uz', sa.String(length=500), nullable=True),
    sa.Column('hero_title_ru', sa.String(length=500), nullable=True),
    sa.Column('hero_title_en', sa.String(length=500), nullable=True),
    sa.Column('hero_subtitle_uz', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_ru', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_en', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('gallery_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('image', sa.String(length=500), nullable=False),
    sa.Column('caption_uz', sa.String(length=300), nullable=False),
    sa.Column('caption_ru', sa.String(length=300), nullable=False),
    sa.Column('caption_en', sa.String(length=300), nullable=False),
    sa.Column('alt_uz', sa.String(length=300), nullable=False),
    sa.Column('alt_ru', sa.String(length=300), nullable=False),
    sa.Column('alt_en', sa.String(length=300), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['gallery_categories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_gallery_items_category_id'), 'gallery_items', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_gallery_items_category_id'), table_name='gallery_items')
    op.drop_table('gallery_items')
    op.drop_table('gallery_page')
    op.drop_index(op.f('ix_gallery_categories_slug'), table_name='gallery_categories')
    op.drop_table('gallery_categories')
    # ### end Alembic commands ###
