"""add structure_page tables

Revision ID: 6c949f611440
Revises: 0007b05c794e
Create Date: 2026-04-09 19:50:19.781948

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '6c949f611440'
down_revision: Union[str, None] = '0007b05c794e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('structure_admin_departments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('head_uz', sa.String(length=255), nullable=True),
    sa.Column('head_ru', sa.String(length=255), nullable=True),
    sa.Column('head_en', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=60), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structure_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('hero_title_uz', sa.String(length=500), nullable=True),
    sa.Column('hero_title_ru', sa.String(length=500), nullable=True),
    sa.Column('hero_title_en', sa.String(length=500), nullable=True),
    sa.Column('hero_subtitle_uz', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_ru', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_en', sa.Text(), nullable=True),
    sa.Column('top_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('top_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('top_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('top_title_uz', sa.String(length=500), nullable=True),
    sa.Column('top_title_ru', sa.String(length=500), nullable=True),
    sa.Column('top_title_en', sa.String(length=500), nullable=True),
    sa.Column('academic_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('academic_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('academic_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('academic_title_uz', sa.String(length=500), nullable=True),
    sa.Column('academic_title_ru', sa.String(length=500), nullable=True),
    sa.Column('academic_title_en', sa.String(length=500), nullable=True),
    sa.Column('academic_lead_uz', sa.Text(), nullable=True),
    sa.Column('academic_lead_ru', sa.Text(), nullable=True),
    sa.Column('academic_lead_en', sa.Text(), nullable=True),
    sa.Column('admin_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('admin_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('admin_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('admin_title_uz', sa.String(length=500), nullable=True),
    sa.Column('admin_title_ru', sa.String(length=500), nullable=True),
    sa.Column('admin_title_en', sa.String(length=500), nullable=True),
    sa.Column('admin_lead_uz', sa.Text(), nullable=True),
    sa.Column('admin_lead_ru', sa.Text(), nullable=True),
    sa.Column('admin_lead_en', sa.Text(), nullable=True),
    sa.Column('services_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('services_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('services_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('services_title_uz', sa.String(length=500), nullable=True),
    sa.Column('services_title_ru', sa.String(length=500), nullable=True),
    sa.Column('services_title_en', sa.String(length=500), nullable=True),
    sa.Column('services_lead_uz', sa.Text(), nullable=True),
    sa.Column('services_lead_ru', sa.Text(), nullable=True),
    sa.Column('services_lead_en', sa.Text(), nullable=True),
    sa.Column('cta_title_uz', sa.String(length=500), nullable=True),
    sa.Column('cta_title_ru', sa.String(length=500), nullable=True),
    sa.Column('cta_title_en', sa.String(length=500), nullable=True),
    sa.Column('cta_text_uz', sa.Text(), nullable=True),
    sa.Column('cta_text_ru', sa.Text(), nullable=True),
    sa.Column('cta_text_en', sa.Text(), nullable=True),
    sa.Column('cta_primary_label_uz', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_label_ru', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_primary_url', sa.String(length=500), nullable=True),
    sa.Column('cta_secondary_label_uz', sa.String(length=120), nullable=True),
    sa.Column('cta_secondary_label_ru', sa.String(length=120), nullable=True),
    sa.Column('cta_secondary_label_en', sa.String(length=120), nullable=True),
    sa.Column('cta_secondary_url', sa.String(length=500), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('structure_support_services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.Column('desc_uz', sa.Text(), nullable=False),
    sa.Column('desc_ru', sa.Text(), nullable=False),
    sa.Column('desc_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('structure_support_services')
    op.drop_table('structure_page')
    op.drop_table('structure_admin_departments')
    # ### end Alembic commands ###
