"""add about_page tables

Revision ID: 955a5651a012
Revises: 4a5b7f5fe65d
Create Date: 2026-04-09 12:58:32.152914

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '955a5651a012'
down_revision: Union[str, None] = '4a5b7f5fe65d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('about_accreditations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=60), nullable=False),
    sa.Column('icon', sa.String(length=60), server_default='ShieldCheckIcon', nullable=False),
    sa.Column('name_uz', sa.String(length=255), nullable=False),
    sa.Column('name_ru', sa.String(length=255), nullable=False),
    sa.Column('name_en', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('about_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('hero_title_uz', sa.String(length=500), nullable=True),
    sa.Column('hero_title_ru', sa.String(length=500), nullable=True),
    sa.Column('hero_title_en', sa.String(length=500), nullable=True),
    sa.Column('hero_subtitle_uz', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_ru', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_en', sa.Text(), nullable=True),
    sa.Column('rector_image', sa.String(length=500), nullable=True),
    sa.Column('rector_name_uz', sa.String(length=255), nullable=True),
    sa.Column('rector_name_ru', sa.String(length=255), nullable=True),
    sa.Column('rector_name_en', sa.String(length=255), nullable=True),
    sa.Column('rector_role_uz', sa.String(length=255), nullable=True),
    sa.Column('rector_role_ru', sa.String(length=255), nullable=True),
    sa.Column('rector_role_en', sa.String(length=255), nullable=True),
    sa.Column('rector_degree_uz', sa.String(length=255), nullable=True),
    sa.Column('rector_degree_ru', sa.String(length=255), nullable=True),
    sa.Column('rector_degree_en', sa.String(length=255), nullable=True),
    sa.Column('rector_letter_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('rector_letter_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('rector_letter_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('rector_letter_title_uz', sa.String(length=500), nullable=True),
    sa.Column('rector_letter_title_ru', sa.String(length=500), nullable=True),
    sa.Column('rector_letter_title_en', sa.String(length=500), nullable=True),
    sa.Column('rector_letter_paragraphs', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('mvv_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('mvv_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('mvv_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('mvv_title_uz', sa.String(length=500), nullable=True),
    sa.Column('mvv_title_ru', sa.String(length=500), nullable=True),
    sa.Column('mvv_title_en', sa.String(length=500), nullable=True),
    sa.Column('mission_uz', sa.Text(), nullable=True),
    sa.Column('mission_ru', sa.Text(), nullable=True),
    sa.Column('mission_en', sa.Text(), nullable=True),
    sa.Column('vision_uz', sa.Text(), nullable=True),
    sa.Column('vision_ru', sa.Text(), nullable=True),
    sa.Column('vision_en', sa.Text(), nullable=True),
    sa.Column('values_uz', sa.Text(), nullable=True),
    sa.Column('values_ru', sa.Text(), nullable=True),
    sa.Column('values_en', sa.Text(), nullable=True),
    sa.Column('address_uz', sa.String(length=500), nullable=True),
    sa.Column('address_ru', sa.String(length=500), nullable=True),
    sa.Column('address_en', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('map_embed_url', sa.String(length=1000), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('about_timeline_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('year', sa.String(length=20), nullable=False),
    sa.Column('title_uz', sa.String(length=300), nullable=False),
    sa.Column('title_ru', sa.String(length=300), nullable=False),
    sa.Column('title_en', sa.String(length=300), nullable=False),
    sa.Column('text_uz', sa.Text(), nullable=False),
    sa.Column('text_ru', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('about_timeline_events')
    op.drop_table('about_page')
    op.drop_table('about_accreditations')
    # ### end Alembic commands ###
