"""add study_forms json to faculty_programs

Revision ID: a43cf4e29655
Revises: 4e322f401000
Create Date: 2026-04-10 09:52:41.964722

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a43cf4e29655'
down_revision: Union[str, None] = '4e322f401000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_programs', sa.Column('study_forms', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), server_default='[]', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_programs', 'study_forms')
    # ### end Alembic commands ###
