"""add international_page tables

Revision ID: a53f649e110c
Revises: 6c949f611440
Create Date: 2026-04-09 20:03:31.785186

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'a53f649e110c'
down_revision: Union[str, None] = '6c949f611440'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('international_page',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hero_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('hero_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('hero_title_uz', sa.String(length=500), nullable=True),
    sa.Column('hero_title_ru', sa.String(length=500), nullable=True),
    sa.Column('hero_title_en', sa.String(length=500), nullable=True),
    sa.Column('hero_subtitle_uz', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_ru', sa.Text(), nullable=True),
    sa.Column('hero_subtitle_en', sa.Text(), nullable=True),
    sa.Column('stat1_value', sa.String(length=40), nullable=True),
    sa.Column('stat1_label_uz', sa.String(length=255), nullable=True),
    sa.Column('stat1_label_ru', sa.String(length=255), nullable=True),
    sa.Column('stat1_label_en', sa.String(length=255), nullable=True),
    sa.Column('stat2_value', sa.String(length=40), nullable=True),
    sa.Column('stat2_label_uz', sa.String(length=255), nullable=True),
    sa.Column('stat2_label_ru', sa.String(length=255), nullable=True),
    sa.Column('stat2_label_en', sa.String(length=255), nullable=True),
    sa.Column('stat3_value', sa.String(length=40), nullable=True),
    sa.Column('stat3_label_uz', sa.String(length=255), nullable=True),
    sa.Column('stat3_label_ru', sa.String(length=255), nullable=True),
    sa.Column('stat3_label_en', sa.String(length=255), nullable=True),
    sa.Column('stat4_value', sa.String(length=40), nullable=True),
    sa.Column('stat4_label_uz', sa.String(length=255), nullable=True),
    sa.Column('stat4_label_ru', sa.String(length=255), nullable=True),
    sa.Column('stat4_label_en', sa.String(length=255), nullable=True),
    sa.Column('programs_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('programs_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('programs_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('programs_title_uz', sa.String(length=500), nullable=True),
    sa.Column('programs_title_ru', sa.String(length=500), nullable=True),
    sa.Column('programs_title_en', sa.String(length=500), nullable=True),
    sa.Column('partners_eyebrow_uz', sa.String(length=255), nullable=True),
    sa.Column('partners_eyebrow_ru', sa.String(length=255), nullable=True),
    sa.Column('partners_eyebrow_en', sa.String(length=255), nullable=True),
    sa.Column('partners_title_uz', sa.String(length=500), nullable=True),
    sa.Column('partners_title_ru', sa.String(length=500), nullable=True),
    sa.Column('partners_title_en', sa.String(length=500), nullable=True),
    sa.Column('cta_title_uz', sa.String(length=500), nullable=True),
    sa.Column('cta_title_ru', sa.String(length=500), nullable=True),
    sa.Column('cta_title_en', sa.String(length=500), nullable=True),
    sa.Column('cta_text_uz', sa.Text(), nullable=True),
    sa.Column('cta_text_ru', sa.Text(), nullable=True),
    sa.Column('cta_text_en', sa.Text(), nullable=True),
    sa.Column('cta_email', sa.String(length=255), nullable=True),
    sa.Column('cta_phone_label', sa.String(length=60), nullable=True),
    sa.Column('cta_phone_url', sa.String(length=60), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('international_partners',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('flag', sa.String(length=20), nullable=False),
    sa.Column('logo_url', sa.String(length=500), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('international_programs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('icon', sa.String(length=60), nullable=False),
    sa.Column('title_uz', sa.String(length=255), nullable=False),
    sa.Column('title_ru', sa.String(length=255), nullable=False),
    sa.Column('title_en', sa.String(length=255), nullable=False),
    sa.Column('desc_uz', sa.Text(), nullable=False),
    sa.Column('desc_ru', sa.Text(), nullable=False),
    sa.Column('desc_en', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('international_programs')
    op.drop_table('international_partners')
    op.drop_table('international_page')
    # ### end Alembic commands ###
