"""enhance faculty_programs with level/study_form/degree/credits/seats

Revision ID: e859d64c0470
Revises: 2a8cdd6313d3
Create Date: 2026-04-09 12:36:57.974640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e859d64c0470'
down_revision: Union[str, None] = '2a8cdd6313d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('faculty_programs', sa.Column('level', sa.String(length=20), server_default='bachelor', nullable=False))
    op.add_column('faculty_programs', sa.Column('study_form', sa.String(length=20), server_default='full_time', nullable=False))
    op.add_column('faculty_programs', sa.Column('degree_uz', sa.String(length=120), server_default='', nullable=False))
    op.add_column('faculty_programs', sa.Column('degree_ru', sa.String(length=120), server_default='', nullable=False))
    op.add_column('faculty_programs', sa.Column('degree_en', sa.String(length=120), server_default='', nullable=False))
    op.add_column('faculty_programs', sa.Column('credits', sa.Integer(), nullable=True))
    op.add_column('faculty_programs', sa.Column('seats', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('faculty_programs', 'seats')
    op.drop_column('faculty_programs', 'credits')
    op.drop_column('faculty_programs', 'degree_en')
    op.drop_column('faculty_programs', 'degree_ru')
    op.drop_column('faculty_programs', 'degree_uz')
    op.drop_column('faculty_programs', 'study_form')
    op.drop_column('faculty_programs', 'level')
    # ### end Alembic commands ###
