"""add events table

Revision ID: f630d7709410
Revises: 491c714276e1
Create Date: 2026-04-08 07:24:43.723411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'f630d7709410'
down_revision: Union[str, None] = '491c714276e1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('title_uz', sa.String(length=500), nullable=False),
    sa.Column('title_ru', sa.String(length=500), nullable=False),
    sa.Column('title_en', sa.String(length=500), nullable=False),
    sa.Column('description_uz', sa.Text(), nullable=False),
    sa.Column('description_ru', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('location_uz', sa.String(length=255), nullable=False),
    sa.Column('location_ru', sa.String(length=255), nullable=False),
    sa.Column('location_en', sa.String(length=255), nullable=False),
    sa.Column('cover_image', sa.String(length=500), nullable=True),
    sa.Column('gallery', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=False),
    sa.Column('meta_title_uz', sa.String(length=255), nullable=True),
    sa.Column('meta_title_ru', sa.String(length=255), nullable=True),
    sa.Column('meta_title_en', sa.String(length=255), nullable=True),
    sa.Column('meta_description_uz', sa.String(length=500), nullable=True),
    sa.Column('meta_description_ru', sa.String(length=500), nullable=True),
    sa.Column('meta_description_en', sa.String(length=500), nullable=True),
    sa.Column('author_id', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_events_slug'), 'events', ['slug'], unique=True)
    op.create_index(op.f('ix_events_starts_at'), 'events', ['starts_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_starts_at'), table_name='events')
    op.drop_index(op.f('ix_events_slug'), table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###
